name: Check bundle size diff

on:
  pull_request:

concurrency:
  group: check-bundle-size-diff-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-bundle-size-diff:
    name: Check bundle size diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: build
          pattern: '.next/static/**/*.{js,css}'
